version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: abdullah
      POSTGRES_PASSWORD: 123qweASD&
      POSTGRES_DB: test
    networks:
      - backend_nest

networks:
  backend_nest:
